# Generated by Django 6.0 on 2026-01-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_favoriteclinic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteClinic',
        ),
    ]
