# Generated by Django 4.2.27 on 2026-02-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_favoriteclinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_start_hour',
            field=models.PositiveSmallIntegerField(default=9),
        ),
    ]
