# Generated by Django 4.2.27 on 2026-02-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_work_start_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
