# Generated by Django 6.0 on 2025-12-17 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카페명')),
                ('url', models.URLField(blank=True, verbose_name='카페 URL')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='카테고리')),
                ('vibe', models.TextField(verbose_name='카페 분위기')),
                ('min_length', models.IntegerField(default=500, verbose_name='최소 글자수')),
                ('max_length', models.IntegerField(default=1500, verbose_name='최대 글자수')),
                ('required_sections', models.JSONField(blank=True, default=list, verbose_name='필수 포함 섹션')),
                ('forbidden_words', models.JSONField(blank=True, default=list, verbose_name='금지 단어')),
                ('recommended_words', models.JSONField(blank=True, default=list, verbose_name='권장 단어')),
                ('title_style', models.TextField(blank=True, verbose_name='제목 스타일 팁')),
                ('image_required', models.BooleanField(default=False, verbose_name='이미지 필수')),
                ('tips', models.TextField(blank=True, verbose_name='작성 팁')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '카페 프로필',
                'verbose_name_plural': '카페 프로필 목록',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='병원명')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='MD 파일 경로')),
                ('location', models.TextField(blank=True, verbose_name='위치')),
                ('hours', models.CharField(blank=True, max_length=200, verbose_name='운영시간')),
                ('parking', models.TextField(blank=True, verbose_name='주차 정보')),
                ('doctors', models.JSONField(blank=True, default=list, verbose_name='의료진 정보')),
                ('consultants', models.JSONField(blank=True, default=list, verbose_name='상담실장 정보')),
                ('price_list', models.JSONField(blank=True, default=list, verbose_name='수가표')),
                ('process', models.TextField(blank=True, verbose_name='상담 프로세스')),
                ('aftercare', models.JSONField(blank=True, default=dict, verbose_name='사후관리')),
                ('post_care', models.JSONField(blank=True, default=dict, verbose_name='수술 후 주의사항')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='병원 특징')),
                ('allowed_hospitals', models.JSONField(blank=True, default=dict, verbose_name='언급 가능 병원')),
                ('blocked_hospitals', models.JSONField(blank=True, default=list, verbose_name='언급 불가 병원')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='파싱 원본 데이터')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '병원 가이드',
                'verbose_name_plural': '병원 가이드 목록',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='페르소나명')),
                ('description', models.TextField(blank=True, verbose_name='설정 설명')),
                ('age_group', models.CharField(max_length=20, verbose_name='연령대')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('speech_style', models.TextField(verbose_name='말투 스타일')),
                ('detail_level', models.CharField(choices=[('detailed', '상세'), ('moderate', '보통'), ('brief', '간결')], default='moderate', max_length=20, verbose_name='상세도')),
                ('emoji_usage', models.BooleanField(default=False, verbose_name='이모지 사용')),
                ('example_phrases', models.JSONField(blank=True, default=list, verbose_name='예시 문구')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='자주 쓰는 키워드')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '페르소나',
                'verbose_name_plural': '페르소나 목록',
            },
        ),
        migrations.CreateModel(
            name='GeneratedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_code', models.CharField(blank=True, max_length=20, verbose_name='담당 원장 코드')),
                ('doctor_name', models.CharField(blank=True, max_length=50, verbose_name='담당 원장명')),
                ('procedure', models.CharField(max_length=100, verbose_name='시술명')),
                ('generated_text', models.TextField(verbose_name='생성된 리뷰')),
                ('prompt_used', models.TextField(blank=True, verbose_name='사용된 프롬프트')),
                ('status', models.CharField(choices=[('generated', '생성됨'), ('edited', '수정됨'), ('uploaded', '업로드완료'), ('rejected', '반려')], default='generated', max_length=20, verbose_name='상태')),
                ('upload_url', models.URLField(blank=True, verbose_name='업로드 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cafe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.cafeprofile', verbose_name='타겟 카페')),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.clinicguide', verbose_name='병원')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.persona', verbose_name='페르소나')),
            ],
            options={
                'verbose_name': '생성 리뷰',
                'verbose_name_plural': '생성 리뷰 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100)),
                ('original_text', models.TextField()),
                ('cleaned_text', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='ko', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sentiment', models.CharField(blank=True, max_length=32, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('insights', models.JSONField(blank=True, default=list)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=1024)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('exif', models.JSONField(blank=True, default=dict)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('caption', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.campaign')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='data.review')),
            ],
        ),
    ]
