# Generated by Django 6.0 on 2025-12-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTypeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True, verbose_name='유형 코드')),
                ('label', models.CharField(max_length=100, verbose_name='유형명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('structure', models.JSONField(blank=True, default=list, verbose_name='글 구조')),
                ('required_sections', models.JSONField(blank=True, default=list, verbose_name='필수 포함 섹션')),
                ('common_expressions', models.JSONField(blank=True, default=list, verbose_name='자주 쓰는 표현')),
                ('opening_patterns', models.JSONField(blank=True, default=list, verbose_name='시작 패턴')),
                ('closing_patterns', models.JSONField(blank=True, default=list, verbose_name='마무리 패턴')),
                ('forbidden_elements', models.JSONField(blank=True, default=list, verbose_name='금지 요소')),
                ('recommended_elements', models.JSONField(blank=True, default=list, verbose_name='권장 요소')),
                ('tone', models.CharField(blank=True, max_length=200, verbose_name='톤')),
                ('emotion_flow', models.JSONField(blank=True, default=list, verbose_name='감정 흐름')),
                ('min_length', models.IntegerField(default=400, verbose_name='최소 글자수')),
                ('max_length', models.IntegerField(default=1200, verbose_name='최대 글자수')),
                ('image_required', models.BooleanField(default=False, verbose_name='이미지 필수')),
                ('tips', models.TextField(blank=True, verbose_name='작성 팁')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '컨텐츠 유형 프로파일',
                'verbose_name_plural': '컨텐츠 유형 프로파일 목록',
                'ordering': ['value'],
            },
        ),
    ]
