# Generated by Django 6.0 on 2025-12-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_llmusagelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmusagelog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='llmusagelog',
            name='tokens',
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='cost_usd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='llmusagelog',
            name='cost_krw',
            field=models.FloatField(default=0.0),
        ),
    ]
