# Generated by Django 6.0 on 2025-12-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_contenttypeprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cafeprofile',
            name='forbidden_words',
        ),
        migrations.RemoveField(
            model_name='cafeprofile',
            name='image_required',
        ),
        migrations.RemoveField(
            model_name='cafeprofile',
            name='max_length',
        ),
        migrations.RemoveField(
            model_name='cafeprofile',
            name='min_length',
        ),
        migrations.RemoveField(
            model_name='cafeprofile',
            name='recommended_words',
        ),
        migrations.RemoveField(
            model_name='cafeprofile',
            name='required_sections',
        ),
        migrations.RemoveField(
            model_name='cafeprofile',
            name='title_style',
        ),
        migrations.RemoveField(
            model_name='cafeprofile',
            name='vibe',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='detail_level',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='example_phrases',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='speech_style',
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='ad_restriction',
            field=models.CharField(choices=[('strict', '엄격'), ('normal', '보통'), ('loose', '느슨')], default='strict', max_length=20, verbose_name='광고 금지 강도'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='board_type',
            field=models.CharField(choices=[('review', '후기게시판'), ('free', '자유게시판'), ('question', '질문게시판')], default='review', max_length=30, verbose_name='게시판 지정'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='cafe_character',
            field=models.CharField(choices=[('info_share', '정보공유형'), ('chat', '수다형'), ('expert', '전문가형'), ('qna', 'Q&A형')], default='info_share', max_length=30, verbose_name='카페 성격'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='forbidden_keywords',
            field=models.JSONField(blank=True, default=list, help_text='협찬/광고/제공/원고료', verbose_name='금지 키워드'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='hashtag_count',
            field=models.CharField(choices=[('none', '없음'), ('under_5', '5개이하'), ('5_10', '5~10'), ('10_15', '10~15'), ('over_15', '15+')], default='5_10', max_length=20, verbose_name='해시태그 개수'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='hospital_name_disclosure',
            field=models.CharField(choices=[('allowed', '가능'), ('initial_only', '이니셜만'), ('forbidden', '불가')], default='allowed', max_length=20, verbose_name='병원명 공개'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='info_request',
            field=models.CharField(blank=True, default='', help_text='궁금한 거 댓글로 / 없음', max_length=100, verbose_name='정보 요청'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='length_range',
            field=models.CharField(choices=[('100_300', '100~300'), ('300_800', '300~800'), ('800_1500', '800~1500'), ('1500_3000', '1500~3000'), ('3000_plus', '3000+')], default='800_1500', max_length=30, verbose_name='글자수 범위'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='paragraph_style',
            field=models.CharField(choices=[('short', '짧은(2~3줄)'), ('medium', '중간'), ('long', '긴 문단')], default='medium', max_length=20, verbose_name='문단 구분'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='photo_mention',
            field=models.CharField(choices=[('full', '사진 첨부'), ('partial', '부분만'), ('none', '언급안함')], default='full', max_length=30, verbose_name='사진 언급 방식'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='photo_required',
            field=models.CharField(choices=[('required', '필수'), ('recommended', '권장'), ('optional', '선택')], default='recommended', max_length=20, verbose_name='사진 필수 여부'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='platform_type',
            field=models.CharField(choices=[('naver_blog', '네이버블로그'), ('cafe', '카페'), ('comment', '댓글'), ('app_review', '앱리뷰'), ('jisin', '지식인')], default='cafe', max_length=30, verbose_name='플랫폼 타입'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='price_disclosure',
            field=models.CharField(choices=[('specific', '가능(구체적)'), ('range_only', '범위만'), ('forbidden', '불가')], default='range_only', max_length=20, verbose_name='가격 공개'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='question_inducement',
            field=models.CharField(blank=True, default='', help_text='혹시 해보신 분? / 없음', max_length=100, verbose_name='질문 유도'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='reply_style',
            field=models.CharField(choices=[('kind_detailed', '친절상세'), ('simple', '간단명료'), ('lazy', '귀찮은척')], default='kind_detailed', max_length=20, verbose_name='답변 스타일'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='required_elements',
            field=models.JSONField(blank=True, default=list, help_text='제목/본문/사진설명/해시태그/별점', verbose_name='필수 포함 요소'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='required_keywords',
            field=models.JSONField(blank=True, default=list, help_text='시술명/병원명/지역명/가격/후기', verbose_name='필수 키워드'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='subtitle_style',
            field=models.CharField(choices=[('square', '■'), ('arrow', '▶'), ('circle', '●'), ('number', '숫자'), ('none', '없음')], default='square', max_length=20, verbose_name='소제목 스타일'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='target_reader',
            field=models.CharField(choices=[('beginner', '초보'), ('experienced', '경험자'), ('expert', '전문가')], default='beginner', max_length=20, verbose_name='대상 독자'),
        ),
        migrations.AddField(
            model_name='cafeprofile',
            name='title_prefix',
            field=models.CharField(choices=[('review', '[후기]'), ('honest', '[솔직]'), ('own_money', '[내돈내산]'), ('none', '없음')], default='none', max_length=30, verbose_name='제목 접두어'),
        ),
        migrations.AddField(
            model_name='contenttypeprofile',
            name='consultation_settings',
            field=models.JSONField(blank=True, default=dict, help_text='\n        {\n            "visit_date": "지난 주 토요일",\n            "reservation_method": "전화/온라인/앱/워크인",\n            "wait_time": "10분",\n            "location_access": "역에서 5분",\n            "interior_vibe": "깔끔/고급/아늑",\n            "cleanliness": "깨끗",\n            "patient_count": "적당",\n            "consultant": "원장직접/실장/상담사",\n            "consultation_time": "30분",\n            "consultation_vibe": "친절/상세/강압적/사무적",\n            "recommended_procedure": "피코레이저 3회",\n            "estimate": "50만원",\n            "push_level": "전혀없음/약간/부담스러움",\n            "explanation_quality": "상세",\n            "booking_status": "당일예약/추후예약/보류/거절",\n            "booking_reason": "믿음이 가서",\n            "hold_reason": "더 알아보려고"\n        }\n        ', verbose_name='방문상담 설정'),
        ),
        migrations.AddField(
            model_name='contenttypeprofile',
            name='content_purpose',
            field=models.CharField(choices=[('info', '정보제공'), ('review', '후기공유'), ('recommend_request', '추천요청'), ('question', '질문'), ('experience', '경험담')], default='review', max_length=30, verbose_name='컨텐츠 목적'),
        ),
        migrations.AddField(
            model_name='contenttypeprofile',
            name='core_message',
            field=models.TextField(blank=True, help_text='전달하고 싶은 1줄 요약', verbose_name='핵심 메시지'),
        ),
        migrations.AddField(
            model_name='contenttypeprofile',
            name='cta_type',
            field=models.CharField(choices=[('comment', '댓글유도'), ('share', '공유유도'), ('inquiry', '병원문의유도'), ('none', '없음')], default='comment', max_length=30, verbose_name='CTA (행동유도)'),
        ),
        migrations.AddField(
            model_name='contenttypeprofile',
            name='emotion_tone',
            field=models.CharField(choices=[('expectation', '기대'), ('worry', '걱정'), ('nervous', '긴장'), ('excited', '설렘'), ('satisfied', '만족'), ('regret', '아쉬움'), ('disappointed', '후회')], default='satisfied', max_length=30, verbose_name='감정 톤'),
        ),
        migrations.AddField(
            model_name='contenttypeprofile',
            name='procedure_day_settings',
            field=models.JSONField(blank=True, default=dict, help_text='\n        {\n            "preparation": "금식/화장 안 하고",\n            "arrival_process": "서류작성/세안/사진촬영",\n            "anesthesia_process": "마취크림 30분/수면마취",\n            "nervousness": "엄청 떨림/좀 긴장/담담",\n            "waiting_environment": "편했어요",\n            "duration": "30분",\n            "pain_level": 3,\n            "pain_description": "따끔/뜨거움/당김/찌릿",\n            "anesthesia_effect": "잘 들어서 괜찮음",\n            "practitioner_attitude": "말 걸어줘서 편함",\n            "mid_check": "거울 확인",\n            "immediate_reaction": "빨개짐/부기/멍/멀쩡",\n            "calming_care": "진정팩/쿨링/연고",\n            "residual_pain": "바로 괜찮음/얼얼함 지속",\n            "can_go_home": "바로 귀가",\n            "can_go_out": "마스크 쓰면",\n            "precautions": ["세안금지", "음주금지", "자외선주의"],\n            "prescription": "연고/먹는약/재생크림",\n            "next_visit": "1주일 뒤 경과체크",\n            "first_impression_score": 5,\n            "vs_expectation": "기대 이상/기대만큼/기대 이하",\n            "next_session_plan": "2주 뒤 2회차"\n        }\n        ', verbose_name='시술당일 설정'),
        ),
        migrations.AddField(
            model_name='contenttypeprofile',
            name='recommend_settings',
            field=models.JSONField(blank=True, default=dict, help_text='\n        {\n            "current_concern": "기미가 점점 진해져서",\n            "procedure_experience": "first/experienced",\n            "budget_range": "50만원 이내",\n            "preferred_region": "강남쪽",\n            "urgency": "이번 주 안에/천천히",\n            "question_type": "병원추천/시술추천/시술비교/부작용질문",\n            "specific_question": "피코 vs 레이저 뭐가 나을까요?",\n            "worry_points": ["통증", "다운타임", "효과"],\n            "wanted_info": ["경험담", "가격정보", "추천병원"]\n        }\n        ', verbose_name='추천받기 설정'),
        ),
        migrations.AddField(
            model_name='contenttypeprofile',
            name='recovery_1month_settings',
            field=models.JSONField(blank=True, default=dict, help_text='\n        {\n            "record_point": "30일",\n            "daily_changes": "1일차: 붓기, 7일차: 회복",\n            "photo_status": "경과 사진 첨부/부분만/없음",\n            "expected_vs_actual": "예상보다 빨리",\n            "actual_downtime": "3~5일",\n            "work_resume": "다음날 출근",\n            "makeup_possible": "3일차",\n            "daily_inconvenience": "세안 조심",\n            "exercise_possible": "1주일 후",\n            "effect_satisfaction": "확실히 효과",\n            "others_reaction": "칭찬받음",\n            "vs_expectation": "기대 이상",\n            "naturalness": "자연스러움",\n            "next_session": "2회차 예약함",\n            "additional_procedure": "다른 시술도",\n            "revisit_intention": "또 갈 예정"\n        }\n        ', verbose_name='시술 후 1개월 설정'),
        ),
        migrations.AddField(
            model_name='contenttypeprofile',
            name='recovery_2month_plus_settings',
            field=models.JSONField(blank=True, default=dict, help_text='\n        {\n            "before_after_comparison": "변화 정도 구체적 서술",\n            "goal_achievement": "80%",\n            "maintenance_duration": "아직 유지",\n            "additional_procedure_needed": "필요없음/유지 시술/보완 필요",\n            "value_for_money": "돈값 함",\n            "total_cost": "회차별/총액/추가비용 포함",\n            "repurchase_intention": "또 할 예정",\n            "price_satisfaction": "비싸도 만족",\n            "recommend_target": "OO 고민인 분들께",\n            "not_recommend_target": "급하신 분",\n            "recommend_level": "강추/추천/보통/비추/강력비추",\n            "revisit_intention": "당연히 또 감",\n            "procedure_tip": "마취 충분히 해달라고",\n            "clinic_selection_tip": "상담 여러 곳 받아보세요",\n            "care_tip": "자외선 차단 필수",\n            "caution": "OO는 피하세요"\n        }\n        ', verbose_name='시술 후 2개월+ 설정'),
        ),
        migrations.AddField(
            model_name='contenttypeprofile',
            name='research_settings',
            field=models.JSONField(blank=True, default=dict, help_text='\n        {\n            "search_method": "카페/블로그/지인추천/광고/앱",\n            "compared_clinics": "3군데",\n            "comparison_criteria": ["가격", "후기", "원장경력", "위치", "장비"],\n            "search_period": "일주일",\n            "clinic_features": "A병원: 저렴, B병원: 유명",\n            "price_comparison": "구체적/범위/비슷비슷",\n            "review_summary": "대체로 만족/호불호 갈림",\n            "decision_status": "고민중/좁혀가는중/거의결정/결정완료",\n            "leaning_toward": "B병원으로 기울어지는 중",\n            "remaining_concern": "가격이 좀 부담"\n        }\n        ', verbose_name='발품/손품 설정'),
        ),
        migrations.AddField(
            model_name='persona',
            name='choice_reason',
            field=models.JSONField(blank=True, default=list, help_text='후기/지인추천/가격/원장경력/위치', verbose_name='선택 이유 표현'),
        ),
        migrations.AddField(
            model_name='persona',
            name='comparison_mention',
            field=models.BooleanField(default=True, verbose_name='비교 언급 여부'),
        ),
        migrations.AddField(
            model_name='persona',
            name='conclusion_expression',
            field=models.CharField(default='결론은 대만족!', max_length=200, verbose_name='결론 표현'),
        ),
        migrations.AddField(
            model_name='persona',
            name='cons_examples',
            field=models.JSONField(blank=True, default=list, help_text='주차불편/대기김/가격높음/위치애매', verbose_name='단점 예시 풀'),
        ),
        migrations.AddField(
            model_name='persona',
            name='cons_mention_style',
            field=models.CharField(choices=[('weak', '약함'), ('medium', '중간'), ('strong', '강함')], default='medium', max_length=20, verbose_name='단점 언급 스타일'),
        ),
        migrations.AddField(
            model_name='persona',
            name='exclamation_freq',
            field=models.CharField(choices=[('high', '높음'), ('medium', '중간'), ('low', '낮음')], default='medium', max_length=20, verbose_name='감탄사 빈도'),
        ),
        migrations.AddField(
            model_name='persona',
            name='experience_level',
            field=models.CharField(choices=[('first', '첫시술'), ('few', '2~3회차'), ('many', '5회이상'), ('regular', '단골')], default='first', max_length=20, verbose_name='경험 레벨'),
        ),
        migrations.AddField(
            model_name='persona',
            name='fear_level',
            field=models.CharField(choices=[('very_scared', '매우겁많음'), ('little', '약간'), ('normal', '보통'), ('brave', '담대함')], default='normal', max_length=20, verbose_name='겁쟁이 정도'),
        ),
        migrations.AddField(
            model_name='persona',
            name='frequent_expressions',
            field=models.JSONField(blank=True, default=list, verbose_name='자주 쓰는 표현 1~3'),
        ),
        migrations.AddField(
            model_name='persona',
            name='honorific_level',
            field=models.CharField(choices=[('formal', '존댓말'), ('informal', '반말'), ('mixed', '혼용')], default='formal', max_length=20, verbose_name='존칭 레벨'),
        ),
        migrations.AddField(
            model_name='persona',
            name='intro_expression',
            field=models.CharField(default='솔직히 처음엔 걱정했는데', max_length=200, verbose_name='인트로 표현'),
        ),
        migrations.AddField(
            model_name='persona',
            name='occupation',
            field=models.CharField(choices=[('office', '직장인'), ('student', '대학생'), ('housewife', '주부'), ('self_employed', '자영업'), ('freelancer', '프리랜서')], default='office', max_length=20, verbose_name='직업/신분'),
        ),
        migrations.AddField(
            model_name='persona',
            name='own_money_emphasis',
            field=models.CharField(choices=[('always', '항상'), ('sometimes', '가끔'), ('never', '안함')], default='always', max_length=20, verbose_name='내돈내산 강조'),
        ),
        migrations.AddField(
            model_name='persona',
            name='price_sensitivity',
            field=models.CharField(choices=[('high', '높음(가성비)'), ('medium', '중간'), ('low', '낮음(퀄리티)')], default='medium', max_length=20, verbose_name='가격 민감도'),
        ),
        migrations.AddField(
            model_name='persona',
            name='recommend_expression',
            field=models.CharField(default='저처럼 겁많은 분들도', max_length=200, verbose_name='추천 표현'),
        ),
        migrations.AddField(
            model_name='persona',
            name='region',
            field=models.CharField(choices=[('seoul', '서울'), ('gyeonggi', '경기'), ('incheon', '인천'), ('busan', '부산'), ('other', '기타 지방')], default='seoul', max_length=20, verbose_name='거주 지역'),
        ),
        migrations.AddField(
            model_name='persona',
            name='sentence_ending',
            field=models.CharField(choices=[('yo', '~요'), ('yong', '~용'), ('dang', '~당'), ('eum', '~음'), ('mixed', '혼용')], default='yo', max_length=20, verbose_name='문장 종결 패턴'),
        ),
        migrations.AddField(
            model_name='persona',
            name='sentence_length',
            field=models.CharField(choices=[('short', '짧은문장'), ('medium', '중간'), ('long', '긴문장')], default='medium', max_length=20, verbose_name='문장 길이'),
        ),
        migrations.AddField(
            model_name='persona',
            name='skin_concerns',
            field=models.JSONField(blank=True, default=list, help_text='기미/잡티/모공/주름/탄력/턱선/코/눈', verbose_name='피부/외모 고민'),
        ),
        migrations.AddField(
            model_name='persona',
            name='skin_type',
            field=models.CharField(choices=[('dry', '건성'), ('oily', '지성'), ('combination', '복합성'), ('sensitive', '민감성')], default='combination', max_length=20, verbose_name='피부 타입'),
        ),
        migrations.AddField(
            model_name='persona',
            name='transition_expression',
            field=models.CharField(default='아무튼!', max_length=200, verbose_name='전환 표현'),
        ),
        migrations.AlterField(
            model_name='cafeprofile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='카페/플랫폼명'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='age_group',
            field=models.CharField(choices=[('20_early', '20대 초반'), ('20_mid', '20대 중반'), ('20_late', '20대 후반'), ('30_early', '30대 초반'), ('30_mid', '30대 중반'), ('30_late', '30대 후반'), ('40_plus', '40대 이상')], max_length=20, verbose_name='연령대'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='emoji_usage',
            field=models.CharField(choices=[('many', '많음'), ('moderate', '적당히'), ('rarely', '거의없음')], default='moderate', max_length=20, verbose_name='이모지 사용'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='gender',
            field=models.CharField(choices=[('female', '여성'), ('male', '남성')], max_length=10, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름/닉네임'),
        ),
    ]
