# Generated by Django 6.0 on 2025-12-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_expanded_presets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenttypeprofile',
            options={'ordering': ['order', 'value'], 'verbose_name': '컨텐츠 유형 프로파일', 'verbose_name_plural': '컨텐츠 유형 프로파일 목록'},
        ),
        migrations.AddField(
            model_name='contenttypeprofile',
            name='order',
            field=models.IntegerField(default=0, verbose_name='정렬 순서'),
        ),
    ]
