# Generated by Django 6.0 on 2025-12-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_add_content_type_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('path', models.CharField(max_length=500, verbose_name='요청 경로')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP 메소드')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referer', models.TextField(blank=True, verbose_name='Referer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='접속 시간')),
            ],
            options={
                'verbose_name': '접속 로그',
                'verbose_name_plural': '접속 로그 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
