# Generated by Django 6.0 on 2026-01-05 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_llmusagelog_options_remove_llmusagelog_tokens_and_more'),
        ('data', '0004_add_content_type_order'),
    ]

    operations = [
    ]
