# Generated by Django 6.0 on 2026-01-08 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('basic', 'Basic'), ('basic_plus', 'Basic Plus'), ('pro_header', 'Pro - 헤더'), ('pro_guidelines', 'Pro - 가이드라인')], max_length=20, verbose_name='모드')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿 이름')),
                ('content', models.TextField(verbose_name='프롬프트 내용')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 템플릿')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='버전')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '프롬프트 템플릿',
                'verbose_name_plural': '프롬프트 템플릿 목록',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='버전')),
                ('content', models.TextField(verbose_name='프롬프트 내용')),
                ('changed_by', models.CharField(blank=True, max_length=100, verbose_name='변경자')),
                ('change_note', models.TextField(blank=True, verbose_name='변경 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='data.prompttemplate')),
            ],
            options={
                'verbose_name': '프롬프트 버전 이력',
                'verbose_name_plural': '프롬프트 버전 이력 목록',
                'ordering': ['-version'],
                'unique_together': {('template', 'version')},
            },
        ),
    ]
