# Generated by Django 6.0 on 2026-01-05 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_merge_20260105_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='예: A, B, 원장1 (없으면 비워도 됨)', max_length=20, verbose_name='원장 코드')),
                ('name', models.CharField(max_length=50, verbose_name='원장명')),
                ('style', models.CharField(blank=True, max_length=200, verbose_name='스타일/설명')),
                ('specialties', models.JSONField(blank=True, default=list, help_text='예: ["눈성형", "코성형"]', verbose_name='전문 분야')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_objects', to='data.clinicguide', verbose_name='병원')),
            ],
            options={
                'verbose_name': '의료진',
                'verbose_name_plural': '의료진 목록',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClinicPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(max_length=100, verbose_name='시술명')),
                ('price_display', models.CharField(blank=True, help_text='예: 50만원 / 30~50만원 / 상담 필요', max_length=50, verbose_name='가격 표시')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_objects', to='data.clinicguide', verbose_name='병원')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='data.clinicdoctor', verbose_name='담당 원장')),
            ],
            options={
                'verbose_name': '수가',
                'verbose_name_plural': '수가 목록',
                'ordering': ['order', 'id'],
            },
        ),
    ]
