# Generated by Django 6.0 on 2026-01-28 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_prompttemplate_prompttemplateversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSeriesBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='배치 이름')),
                ('user_input', models.TextField(verbose_name='사용자 입력')),
                ('content_types', models.JSONField(default=list, verbose_name='컨텐츠 타입 목록')),
                ('model_used', models.CharField(default='claude-sonnet-4-5-20250929', max_length=100, verbose_name='사용 모델')),
                ('target_count', models.IntegerField(default=30, verbose_name='목표 생성 수')),
                ('completed_count', models.IntegerField(default=0, verbose_name='완료 수')),
                ('status', models.CharField(choices=[('pending', '대기'), ('in_progress', '진행중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('total_input_tokens', models.IntegerField(default=0, verbose_name='총 입력 토큰')),
                ('total_output_tokens', models.IntegerField(default=0, verbose_name='총 출력 토큰')),
                ('total_cost_usd', models.FloatField(default=0.0, verbose_name='총 비용 (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Multi 배치',
                'verbose_name_plural': 'Multi 배치 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='시술명')),
                ('category', models.CharField(choices=[('skin', '피부 시술'), ('injection', '주사/필러'), ('laser', '레이저'), ('lifting', '리프팅'), ('body', '바디'), ('hair', '모발'), ('etc', '기타')], default='skin', max_length=20, verbose_name='카테고리')),
                ('description', models.TextField(blank=True, verbose_name='시술 설명')),
                ('pain_level', models.CharField(choices=[('none', '거의 없음'), ('mild', '약간'), ('moderate', '보통'), ('high', '높음'), ('very_high', '매우 높음')], default='moderate', max_length=20, verbose_name='통증 레벨')),
                ('recovery_time', models.CharField(blank=True, max_length=100, verbose_name='회복 기간')),
                ('typical_results', models.TextField(blank=True, verbose_name='일반적 결과')),
                ('common_side_effects', models.JSONField(blank=True, default=list, verbose_name='일반적 부작용')),
                ('precautions', models.JSONField(blank=True, default=list, verbose_name='주의사항')),
                ('price_range', models.CharField(blank=True, max_length=100, verbose_name='가격 범위')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='시술 시간')),
                ('anesthesia_type', models.CharField(blank=True, max_length=100, verbose_name='마취 방법')),
                ('sessions_recommended', models.CharField(blank=True, max_length=100, verbose_name='권장 회차')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '시술 정보',
                'verbose_name_plural': '시술 정보 목록',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='mode',
            field=models.CharField(choices=[('basic', 'Basic'), ('basic_plus', 'Basic Plus'), ('basic_multi', 'Basic Multi'), ('basic_multi_title', 'Basic Multi - 제목'), ('basic_multi_score', 'Basic Multi - 점수'), ('pro_header', 'Pro - 헤더'), ('pro_guidelines', 'Pro - 가이드라인'), ('app_gangnam', '앱 - 강남언니')], max_length=30, verbose_name='모드'),
        ),
        migrations.CreateModel(
            name='MultiSeriesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_index', models.IntegerField(verbose_name='시리즈 번호')),
                ('persona_settings', models.JSONField(blank=True, default=dict, verbose_name='페르소나 설정')),
                ('situation_settings', models.JSONField(blank=True, default=dict, verbose_name='상황 설정')),
                ('temperature', models.FloatField(default=0.85, verbose_name='Temperature')),
                ('pieces', models.JSONField(default=list, verbose_name='컨텐츠 피스 목록')),
                ('naturalness_score', models.FloatField(blank=True, null=True, verbose_name='자연스러움 점수')),
                ('score_feedback', models.TextField(blank=True, verbose_name='점수 피드백')),
                ('prompt_used', models.TextField(blank=True, verbose_name='사용된 프롬프트')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='입력 토큰')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='출력 토큰')),
                ('cost_usd', models.FloatField(default=0.0, verbose_name='비용 (USD)')),
                ('status', models.CharField(choices=[('generated', '생성됨'), ('scored', '점수완료'), ('edited', '편집됨'), ('scheduled', '스케줄됨'), ('exported', '내보냄')], default='generated', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data.multiseriesbatch', verbose_name='배치')),
            ],
            options={
                'verbose_name': 'Multi 시리즈',
                'verbose_name_plural': 'Multi 시리즈 목록',
                'ordering': ['batch', 'series_index'],
            },
        ),
        migrations.AddField(
            model_name='multiseriesbatch',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.procedureinfo', verbose_name='시술'),
        ),
    ]
