# Generated by Django 6.0 on 2026-01-09 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_clinicdoctor_clinicprice'),
        ('data', '0006_prompttemplate_prompttemplateversion'),
    ]

    operations = [
    ]
