# Generated by Django 6.0 on 2026-01-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_merge_20260109_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='mode',
            field=models.CharField(choices=[('basic', 'Basic'), ('basic_plus', 'Basic Plus'), ('pro_header', 'Pro - 헤더'), ('pro_guidelines', 'Pro - 가이드라인'), ('app_gangnam', '앱 - 강남언니')], max_length=20, verbose_name='모드'),
        ),
    ]
