# Generated by Django 6.0 on 2026-01-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_multiseriesbatch_procedureinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureinfo',
            name='knowledge_base',
            field=models.JSONField(blank=True, default=dict, help_text='AI 수집 또는 수동 입력된 체험 기반 지식 (감각, 감정, 커뮤니티 표현 등)', verbose_name='체험 지식 DB'),
        ),
    ]
