# Generated by Django 6.0 on 2026-01-29 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_procedureinfo_knowledge_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(verbose_name='라운드 번호')),
                ('prompt_content', models.TextField(verbose_name='이 라운드의 프롬프트')),
                ('prompt_changes', models.TextField(blank=True, verbose_name='이전 대비 변경사항')),
                ('analysis_result', models.JSONField(blank=True, default=dict, verbose_name='분석 결과 상세')),
                ('score_ai_detection', models.FloatField(blank=True, null=True, verbose_name='AI탐지 회피 점수')),
                ('score_naturalness', models.FloatField(blank=True, null=True, verbose_name='자연스러움 점수')),
                ('score_diversity', models.FloatField(blank=True, null=True, verbose_name='다양성 점수')),
                ('score_accuracy', models.FloatField(blank=True, null=True, verbose_name='정보 정확도 점수')),
                ('score_overall', models.FloatField(blank=True, null=True, verbose_name='종합 점수')),
                ('analysis_feedback', models.TextField(blank=True, verbose_name='분석 피드백')),
                ('suggested_prompt', models.TextField(blank=True, verbose_name='AI 제안 프롬프트')),
                ('suggested_changes', models.TextField(blank=True, verbose_name='제안 변경 설명')),
                ('approved_prompt', models.TextField(blank=True, verbose_name='승인된 프롬프트')),
                ('status', models.CharField(choices=[('pending', '대기'), ('generating', '생성중'), ('generated', '생성완료'), ('analyzing', '분석중'), ('analyzed', '분석완료'), ('approved', '승인됨'), ('rejected', '거부됨')], default='pending', max_length=20, verbose_name='상태')),
                ('generated_count', models.IntegerField(default=0, verbose_name='생성된 샘플 수')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='입력 토큰')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='출력 토큰')),
                ('cost_usd', models.FloatField(default=0.0, verbose_name='비용 (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '최적화 라운드',
                'verbose_name_plural': '최적화 라운드 목록',
                'ordering': ['session', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_index', models.IntegerField(verbose_name='샘플 번호')),
                ('persona_settings', models.JSONField(blank=True, default=dict, verbose_name='페르소나 설정')),
                ('generated_content', models.TextField(verbose_name='생성된 컨텐츠')),
                ('individual_scores', models.JSONField(blank=True, default=dict, help_text="{'ai_detection': 8.5, 'naturalness': 9.0, ...}", verbose_name='개별 점수')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='입력 토큰')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='출력 토큰')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='data.optimizationround', verbose_name='라운드')),
            ],
            options={
                'verbose_name': '최적화 샘플',
                'verbose_name_plural': '최적화 샘플 목록',
                'ordering': ['round', 'sample_index'],
            },
        ),
        migrations.CreateModel(
            name='PromptOptimizationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='세션명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('user_input', models.TextField(blank=True, help_text='시술/병원/상황 등 컨텍스트 정보', verbose_name='사용자 입력')),
                ('samples_per_round', models.IntegerField(default=50, verbose_name='라운드당 샘플 수')),
                ('target_rounds', models.IntegerField(default=5, verbose_name='목표 라운드 수')),
                ('mode', models.CharField(choices=[('semi_auto', '반자동'), ('auto', '자동')], default='semi_auto', max_length=20, verbose_name='실행 모드')),
                ('auto_approve_threshold', models.FloatField(default=8.0, help_text='자동 모드에서 이 점수 이상이면 자동 승인', verbose_name='자동 승인 점수')),
                ('model_used', models.CharField(default='claude-sonnet-4-5-20250929', max_length=100, verbose_name='생성 모델')),
                ('analysis_model', models.CharField(default='claude-sonnet-4-5-20250929', max_length=100, verbose_name='분석 모델')),
                ('analyze_ai_detection', models.BooleanField(default=True, verbose_name='AI 탐지 회피 분석')),
                ('analyze_naturalness', models.BooleanField(default=True, verbose_name='자연스러움 분석')),
                ('analyze_diversity', models.BooleanField(default=True, verbose_name='다양성 분석')),
                ('analyze_accuracy', models.BooleanField(default=True, verbose_name='정보 정확도 분석')),
                ('status', models.CharField(choices=[('created', '생성됨'), ('in_progress', '진행중'), ('completed', '완료'), ('paused', '일시정지')], default='created', max_length=20, verbose_name='상태')),
                ('current_round', models.IntegerField(default=0, verbose_name='현재 라운드')),
                ('total_input_tokens', models.IntegerField(default=0, verbose_name='총 입력 토큰')),
                ('total_output_tokens', models.IntegerField(default=0, verbose_name='총 출력 토큰')),
                ('total_cost_usd', models.FloatField(default=0.0, verbose_name='총 비용 (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.prompttemplate', verbose_name='기본 프롬프트 템플릿')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.procedureinfo', verbose_name='시술 정보')),
            ],
            options={
                'verbose_name': '최적화 세션',
                'verbose_name_plural': '최적화 세션 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='optimizationround',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='data.promptoptimizationsession', verbose_name='세션'),
        ),
        migrations.CreateModel(
            name='OptimizationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('info', '정보'), ('generation', '생성'), ('analysis', '분석'), ('approval', '승인'), ('error', '오류')], default='info', max_length=20, verbose_name='로그 타입')),
                ('message', models.TextField(verbose_name='메시지')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='상세 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='data.optimizationround', verbose_name='라운드')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='data.promptoptimizationsession', verbose_name='세션')),
            ],
            options={
                'verbose_name': '최적화 로그',
                'verbose_name_plural': '최적화 로그 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='optimizationround',
            unique_together={('session', 'round_number')},
        ),
    ]
