# Generated by Django 6.0 on 2026-01-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_optimizationround_optimizationsample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureinfo',
            name='raw_knowledge_entries',
            field=models.JSONField(blank=True, default=list, help_text='수집한 원본 텍스트 목록. 나중에 일괄 파싱 가능.', verbose_name='원본 수집 데이터'),
        ),
        migrations.AlterField(
            model_name='procedureinfo',
            name='knowledge_base',
            field=models.JSONField(blank=True, default=dict, help_text='파싱된 체험 기반 지식 (감각, 감정, 커뮤니티 표현 등)', verbose_name='체험 지식 DB (파싱됨)'),
        ),
    ]
