# Generated by Django 6.0 on 2026-01-14 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_dailyworklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('opinion', '여론'), ('review', '후기')], db_index=True, max_length=20)),
                ('platform', models.CharField(choices=[('all', '전체'), ('naver', '네이버'), ('gn_jp', 'JP강남언니'), ('gangnam', '강남언니'), ('babytok', '바비톡'), ('yeoshin', '여신티켓'), ('seongyesa', '성예사'), ('dadamo', '대다모')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('views', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('normal', '정상'), ('hot', '반응중'), ('issue', '이슈'), ('managed', '대응완료')], db_index=True, default='normal', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='data.clinicguide')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['clinic', 'type', 'platform'], name='data_clinic_clinic__55ec58_idx'), models.Index(fields=['clinic', 'type', '-updated_at'], name='data_clinic_clinic__42822c_idx')],
            },
        ),
    ]
