# Generated by Django 6.0 on 2026-01-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_add_raw_knowledge_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptoptimizationsession',
            name='analysis_depth',
            field=models.CharField(choices=[('basic', '기본'), ('detailed', '상세'), ('exhaustive', '정밀')], default='detailed', max_length=20, verbose_name='분석 깊이'),
        ),
        migrations.AddField(
            model_name='promptoptimizationsession',
            name='max_tokens_analysis',
            field=models.IntegerField(default=8000, verbose_name='분석 최대 토큰'),
        ),
        migrations.AddField(
            model_name='promptoptimizationsession',
            name='max_tokens_generation',
            field=models.IntegerField(default=4000, verbose_name='생성 최대 토큰'),
        ),
        migrations.AddField(
            model_name='promptoptimizationsession',
            name='persona_options',
            field=models.JSONField(blank=True, default=dict, help_text='age_groups, genders, tones, experiences 등', verbose_name='페르소나 옵션'),
        ),
        migrations.AddField(
            model_name='promptoptimizationsession',
            name='style_options',
            field=models.JSONField(blank=True, default=dict, help_text='이모지, 문장길이, 포맷 등', verbose_name='스타일 옵션'),
        ),
        migrations.AddField(
            model_name='promptoptimizationsession',
            name='temperature_max',
            field=models.FloatField(default=0.95, verbose_name='최대 온도'),
        ),
        migrations.AddField(
            model_name='promptoptimizationsession',
            name='temperature_min',
            field=models.FloatField(default=0.7, verbose_name='최소 온도'),
        ),
    ]
