# Generated by Django 6.0 on 2026-02-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_add_optimization_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiseriesbatch',
            name='persona_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='페르소나 설정'),
        ),
        migrations.AddField(
            model_name='multiseriesbatch',
            name='situation_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='상황 설정'),
        ),
        migrations.AddField(
            model_name='multiseriesbatch',
            name='temperature',
            field=models.FloatField(default=0.85, verbose_name='Temperature'),
        ),
    ]
