# Generated by Django 6.0 on 2026-01-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_clinicpost_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicpost',
            name='platform',
            field=models.CharField(choices=[('all', '전체'), ('naver', '네이버'), ('gn_jp', 'JP강남언니'), ('gangnam', '강남언니'), ('babytok', '바비톡'), ('todaktok', '토닥톡'), ('yeoshin', '여신티켓'), ('seongyesa', '성예사'), ('dadamo', '대다모')], db_index=True, max_length=30),
        ),
    ]
