# Generated by Django 6.0 on 2026-01-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_calendar_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarmemo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
