# Generated by Django 6.0 on 2026-01-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_alter_calendarmemo_id'),
        ('data', '0022_calendarmemo_platform'),
    ]

    operations = [
    ]
