# Generated by Django 6.0 on 2026-01-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_calendarmemo_account_fields'),
        ('data', '0023_merge_20260121_1810'),
    ]

    operations = [
    ]
