# Generated by Django 6.0 on 2026-01-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_merge_20260121_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicpost',
            name='review_subtype',
            field=models.CharField(blank=True, choices=[('text', '텍스트 후기'), ('photo', '사진 후기'), ('consultation', '상담 후기')], db_index=True, max_length=20, null=True),
        ),
    ]
