# Generated by Django 6.0 on 2026-01-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_alter_clinicpost_review_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicpost',
            name='opinion_subtype',
            field=models.CharField(blank=True, choices=[('concern', '고민'), ('hand', '손품'), ('foot', '발품')], db_index=True, max_length=20, null=True),
        ),
    ]
