# Generated by Django 4.2.27 on 2026-01-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_crawledpostcontent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='crawledpostcontent',
            new_name='data_crawle_platfor_fecf2a_idx',
            old_name='data_crawl_platform_3a1e3a_idx',
        ),
        migrations.AddField(
            model_name='generatedreview',
            name='title_suggestions',
            field=models.JSONField(blank=True, default=list, verbose_name='제목 추천'),
        ),
    ]
