# Generated by Django 5.1.4 on 2026-02-03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0030_rename_data_crawl_platform_3a1e3a_idx_data_crawle_platfor_fecf2a_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("work_date", models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ("check_in_at", models.DateTimeField(blank=True, null=True)),
                ("check_out_at", models.DateTimeField(blank=True, null=True)),
                ("worked_minutes", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("working", "근무중"), ("completed", "퇴근")], db_index=True, default="working", max_length=20)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_records", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-work_date", "-updated_at"],
                "unique_together": {("user", "work_date")},
            },
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["user", "work_date"], name="data_atten_user_id_d6f860_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["work_date", "status"], name="data_atten_work_da_757eab_idx"),
        ),
    ]

