# Generated by Django 5.1.4 on 2026-02-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0031_attendancerecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceCorrectionRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("work_date", models.DateField(db_index=True)),
                ("current_check_in_at", models.DateTimeField(blank=True, null=True)),
                ("current_check_out_at", models.DateTimeField(blank=True, null=True)),
                ("requested_check_in_at", models.DateTimeField(blank=True, null=True)),
                ("requested_check_out_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("status", models.CharField(choices=[("pending", "대기"), ("approved", "승인"), ("rejected", "반려")], db_index=True, default="pending", max_length=20)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="correction_requests", to="data.attendancerecord")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_attendance_corrections", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_correction_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="attendancecorrectionrequest",
            index=models.Index(fields=["user", "work_date"], name="data_atten_user_id_69d0f5_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancecorrectionrequest",
            index=models.Index(fields=["status", "-created_at"], name="data_atten_status_e6fc9b_idx"),
        ),
    ]

