# Generated by Django 4.2.27 on 2026-02-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_internalmessageattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancecorrectionrequest',
            new_name='data_attend_user_id_7568e7_idx',
            old_name='data_atten_user_id_69d0f5_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancecorrectionrequest',
            new_name='data_attend_status_5379d9_idx',
            old_name='data_atten_status_e6fc9b_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='data_attend_user_id_60d88b_idx',
            old_name='data_atten_user_id_d6f860_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='data_attend_work_da_75796e_idx',
            old_name='data_atten_work_da_757eab_idx',
        ),
        migrations.RenameIndex(
            model_name='internalmessage',
            new_name='data_intern_recipie_bca054_idx',
            old_name='data_inter_recipie_bf0524_idx',
        ),
        migrations.RenameIndex(
            model_name='internalmessage',
            new_name='data_intern_sender__1037cd_idx',
            old_name='data_inter_sender__8eb588_idx',
        ),
    ]
