# Generated by Django 5.1.4 on 2026-02-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0035_rename_data_atten_user_id_69d0f5_idx_data_attend_user_id_7568e7_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(choices=[("attendance_requests_access", "근태 정정요청 접근"), ("web_dashboard_access", "웹 대시보드 접근")], db_index=True, max_length=64)),
                ("is_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_system_permissions", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="system_permissions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "시스템 권한",
                "verbose_name_plural": "시스템 권한",
                "ordering": ["user_id", "key"],
                "unique_together": {("user", "key")},
            },
        ),
    ]

