# Generated by Django 4.2.27 on 2026-02-06 01:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0036_systempermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('type', models.CharField(choices=[('annual', '연차'), ('half_am', '오전반차'), ('half_pm', '오후반차')], db_index=True, default='annual', max_length=20)),
                ('days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '반려')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vacation_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'start_date'], name='data_vacati_user_id_cf5c59_idx'), models.Index(fields=['status', '-created_at'], name='data_vacati_status_beda5e_idx')],
            },
        ),
    ]
