# Generated by Django 4.2.27 on 2026-02-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_vacationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempermission',
            name='key',
            field=models.CharField(choices=[('attendance_requests_access', '근태 정정요청 접근'), ('web_dashboard_access', '웹 대시보드 접근'), ('vacation_admin_access', '휴가 관리 접근'), ('employee_management_access', '직원 관리 접근')], db_index=True, max_length=64),
        ),
    ]
