# Generated by Django 4.2.27 on 2026-02-09 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_alter_systempermission_key'),
    ]

    operations = [
    ]
