# Generated by Django 4.2.27 on 2026-02-12 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0041_merge_20260209_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('plan_id', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('plan_title', models.CharField(blank=True, default='', max_length=200)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('detail', models.TextField(blank=True, default='')),
                ('draft', models.TextField(blank=True, default='')),
                ('account', models.CharField(blank=True, default='', max_length=100)),
                ('account_password', models.CharField(blank=True, default='', max_length=100)),
                ('remind_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_schedules', to='data.clinicguide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='data_review_user_id_05512f_idx'), models.Index(fields=['user', 'is_read'], name='data_review_user_id_feeca6_idx'), models.Index(fields=['plan_id'], name='data_review_plan_id_cb18d0_idx')],
            },
        ),
    ]
