# Generated by Django 4.2.27 on 2026-02-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_reviewschedulememo_reviewschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicpost',
            name='crawled_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
