# Generated by Django 4.2.27 on 2026-02-12 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_reviewschedulememo_clinicpost_crawled_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewScheduleMemo',
            fields=[
            ],
            options={
                'verbose_name': '리뷰 설계안',
                'verbose_name_plural': '리뷰 설계안',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('data.calendarmemo',),
        ),
    ]
