# Generated by Django 4.2.27 on 2026-02-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_cliniccommentbundle_and_remove_post_comment_bundles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliniccommentbundle',
            options={'ordering': ['-created_at'], 'verbose_name': '콘텐츠 댓글', 'verbose_name_plural': '콘텐츠 댓글'},
        ),
        migrations.AlterModelOptions(
            name='internalmessage',
            options={'ordering': ['-created_at'], 'verbose_name': '메일', 'verbose_name_plural': '메일'},
        ),
        migrations.AlterModelOptions(
            name='internalmessageattachment',
            options={'ordering': ['id'], 'verbose_name': '메일 첨부', 'verbose_name_plural': '메일 첨부'},
        ),
        migrations.RenameIndex(
            model_name='cliniccommentbundle',
            new_name='data_clinic_clinic__73a196_idx',
            old_name='data_clinic_clinic__9cf239_idx',
        ),
    ]
