# Generated by Django 4.2.27 on 2026-02-19 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_alter_cliniccommentbundle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliniccommentbundle',
            options={'ordering': ['-created_at'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
    ]
