# Generated by Django 4.2.27 on 2026-02-19 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data", "0048_alter_cliniccommentbundle_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicMessageLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(max_length=1000)),
                ("platform", models.CharField(blank=True, db_index=True, default="", max_length=30)),
                (
                    "message_type",
                    models.CharField(
                        choices=[("prev_opinion", "지난여론쪽지"), ("comment_work", "댓글작업쪽지")],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_logs",
                        to="data.clinicguide",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinic_message_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "쪽지",
                "verbose_name_plural": "쪽지",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["clinic", "-created_at"], name="data_clinic_clinic__7a28e8_idx"),
                    models.Index(fields=["clinic", "message_type", "-created_at"], name="data_clinic_clinic__13e7ee_idx"),
                ],
            },
        ),
    ]
