# Generated by Django 4.2.27 on 2026-02-20 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_globalnotice_and_read'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clinicmessagelog',
            new_name='data_clinic_clinic__fe16ed_idx',
            old_name='data_clinic_clinic__7a28e8_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicmessagelog',
            new_name='data_clinic_clinic__158eab_idx',
            old_name='data_clinic_clinic__13e7ee_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicnotice',
            new_name='data_clinic_clinic__b4813f_idx',
            old_name='data_cn_clinic_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicnotice',
            new_name='data_clinic_clinic__7daf4b_idx',
            old_name='data_cn_pin_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicnoticeread',
            new_name='data_clinic_user_id_5aa9d4_idx',
            old_name='data_cnr_user_notice_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicnoticeread',
            new_name='data_clinic_notice__506f85_idx',
            old_name='data_cnr_notice_user_idx',
        ),
        migrations.RenameIndex(
            model_name='globalnotice',
            new_name='data_global_updated_23028b_idx',
            old_name='data_gn_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='globalnotice',
            new_name='data_global_is_pinn_00cb27_idx',
            old_name='data_gn_pin_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='globalnoticeread',
            new_name='data_global_user_id_1f2ca2_idx',
            old_name='data_gnr_user_notice_idx',
        ),
        migrations.RenameIndex(
            model_name='globalnoticeread',
            new_name='data_global_notice__d9b799_idx',
            old_name='data_gnr_notice_user_idx',
        ),
    ]
